### ISSUE TITLE
Compilation Problems (linux)

### ISSUE THREAD

**Issue by mttnff** [mmjb/T2#15]
I'm trying to compile T2 on linux for research purposes. I followed the `README.txt` and installed fsharp, z3 (including .NET bindings) without any problems. However, the final `xbuild` in T2/src gives the following error:
```
error : /.../T2/src/T2-Library.fsproj: The required attribute "Project" in Import is empty
```

I am not familiar with `xbuild`, but I tried this suggestion http://stackoverflow.com/questions/21998962/building-vs2013-f-project-on-heroku-fails-with-the-required-attribute-project (replaced the Choose tag as in the answer), which appeared to work, but later on I got again an error:
```
/.../T2/src/T2-CLI.fsproj: error : Target named 'Build' not found in the project.
```

My version of xbuild:
```
xbuild /version
XBuild Engine Version 12.0
Mono, Version 4.2.1.0
```

Any help is very appreciated.

**Comment by mmjb** [comment]
Sorry, I fear I don't see the solution to this directly. I expect that including the standard msbuild targets (which include the Build target that seems to be missing) fails. If you have a working locate (or alternatively, searching in /usr/lib/mono): Do you have a file called "Microsoft.FSharp.Targets" somewhere? It should come with your fsharp installation (on Debian-based systems like Ubuntu, dpkg -L fsharp should show it).

Alternatively: Is that on some standard Linux distribution, so that I can try to reproduce this?

**Comment by mttnff** [comment]
Thanks for your answer. This is on openSUSE 13.2. If this might be related to some broken packages, I can also try this on an Arch machine tomorrow. I have the file in several locations:
```
/usr/lib/mono/4.5/Microsoft.FSharp.Targets
/usr/lib/mono/Microsoft SDKs/F#/3.1/Framework/v4.0/Microsoft.FSharp.Targets
/usr/lib/mono/Microsoft SDKs/F#/4.0/Framework/v4.0/Microsoft.FSharp.Targets
/usr/lib/mono/Microsoft SDKs/F#/3.0/Framework/v4.0/Microsoft.FSharp.Targets
/usr/lib/mono/Microsoft F#/v4.0/Microsoft.FSharp.Targets
```
which are all includes of the first one. All of these are indeed part of the "fsharp" package (not part of the standard repo, so there might be some issues with that, although the unstable repos usually work quite well). I was able to compile z3 using `xbuild`, so at least something is working ;)

If it is of any help I can post the contents of this file or a log of xbuild with a higher verbosity level.

**Comment by mmjb** [comment]
So if you have a pressing deadline, I would recommend using a current Debian/Ubuntu installation, which are known to work. Building z3 only exercises the C# bits, but it shows that your mono installation is working in general. F# is slightly more arcane, and more things tend to break there. 

I guess that the packaging of fsharp is broken here. The build file tries to include "$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\FSharp\Microsoft.FSharp.Targets". On Windows, this is the canonical path. On Debian/Ubuntu, $(VisualStudioVersion) is the empty string, but there's a /usr/lib/mono/xbuild/Microsoft/VisualStudio/v/... (no version number) to take care of that.
I didn't have the time to set up an OpenSuse system, but you may have success with the xbuild-fixes branch that I just published (it just adds one more location to look for the .Targets file).

**Comment by mttnff** [comment]
The xbuild-fixes branch indeed fixes the problem; compilation was succesful and T2 seems to run fine. Thanks a lot for your efforts!

**Comment by mmjb** [comment]
For the record, I've now merge these changes into the master branch.
